.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH IGOTU2GPX 1 "March 24, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
igotu2gpx \- command line interface ot the i-gotU gps trackers
.SH SYNOPSIS
.B igotu2gpx dump|info [\fIOPTIONS\fR]
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
.PP
\fBigotu2gpx\fP gives access to the i-gotU gps trackers via serial port
(Windows) or libusb (Linux). It is possible to dump the internal flash memory
and to export tracks and waypoints in gpx format.
.TP
\fB\-\-help\fR
help message
.TP
\fB\-i\fR, \fB\-\-image\fR \fIfile\fR
instead of connecting to the gps tracker, use the specified image file (saved
by "dump \-\-raw")
.TP
\fB\-u\fR, \fB\-\-usb\-device\fR \fIvendor:product\fR
connect via usb to the device specified by vendor:product (this is the default
on Linux)
.\".TP
.\"\fB\-s\fR, \fB\-\-serial\-device\fR \fIport\fR
.\"connect via RS232 to the serial port with the specfied number (this is the
.\"default on Windows)
.TP
\fB\-\-gpx\fR
output in gpx format (this is the default)
.TP
\fB\-\-details\fR
output a detailed representation of the track
.TP
\fB\-\-raw\fR \fIfile\fR
output the raw flash contents of the gps tracker
.TP
\fB\-\-action\fR \fIaction\fR
dump the trackpoints (dump) or show general info (info)
.SH AUTHOR
igotu2gpx was written by Michael Hofmann <mh21@piware.de>.
.SH "REPORTING BUGS"
Report bugs at https://bugs.launchpad.net/igotu2gpx/.
.SH COPYRIGHT
Copyright \(co 2009 Michael Hofmann <mh21@piware.de>.
.br
This is free software. You may redistribute copies of it under the terms of the
GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
http://mh21.de/igotu2gpx/
